#!/bin/bash
#SBATCH --job-name=MUMer # Job name
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=sisi.chen@ufl.edu    # Where to send mail
#SBATCH --cpus-per-task=40
#SBATCH --mem-per-cpu=5g
#SBATCH --time=96:00:00              # Time limit hrs:min:sec
#SBATCH --output=mumer_%j.log # Standard output and error log
#SBATCH --qos=xingbo.wu-b
date;hostname;pwd

module load mummer
    ####MUMmer    
    
####Whole genome alignment. Any other alignment can also be used.
nucmer --maxmatch -c 100 -b 500 -l 50 -t 40 /blue/xingbo.wu/sisi.chen/02.avacado/01.assem/Chr_geno/hass_Chr.fa /blue/xingbo.wu/sisi.chen/02.avacado/01.assem/Chr_geno/WestIndian_Chr.fa
####Remove small and lower quality alignments
delta-filter -m -i 90 -l 100 out.delta > WestIndian_i90_m_delta.filter
####Convert alignment information to a .TSV format as required by SyRI
show-coords -THrd WestIndian_i90_m_delta.filter > WestIndian_i90_m_delta.filter.coords

    ####syri
module load minimap2
####Using minimap2 for generating alignment. Any other whole genome alignment tool can also be used.
minimap2 -ax asm5 --eqx /blue/xingbo.wu/sisi.chen/02.avacado/01.assem/Chr_geno/hass_Chr.fa /blue/xingbo.wu/sisi.chen/02.avacado/01.assem/Chr_geno/WestIndian_Chr.fa> hass_WestIndian.sam -t 40
####syri will output the genome structure difference files syri.out and syri.vcf
module load conda
conda activate syri_env

python3 /apps/syri/1.5.4/bin/syri -c hass_WestIndian.sam -r /blue/xingbo.wu/sisi.chen/02.avacado/01.assem/Chr_geno/hass_Chr.fa -q /blue/xingbo.wu/sisi.chen/02.avacado/01.assem/Chr_geno/WestIndian_Chr.fa -k -F S --prefix WestIndian
####Identification of genome rearrangements from whole-genome comparisons generated by MUMmer using SyRI
python3 /apps/syri/1.5.4/bin/syri -c WestIndian_i90_m_delta.filter.coords -d WestIndian_i90_m_delta.filter -r /blue/xingbo.wu/sisi.chen/02.avacado/01.assem/Chr_geno/hass_Chr.fa -q /blue/xingbo.wu/sisi.chen/02.avacado/01.assem/Chr_geno/WestIndian_Chr.fa 

####plot the results

module load conda
conda activate sisiconda
module load syri
python3 /apps/plotsr/0.5.4/bin/plotsr  --sr WestIndiansyri.out --genomes genomes.txt -H 8 -W 5 -o hass_WestIndian.pdf


date
